name: 'publish'

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bump-version-and-publish:
    if: ${{ github.actor != 'github-actions[bot]' }}
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Bump version
        id: bump_version
        run: |
          bump_type=$(git log -1 --pretty=%B | grep -Eo '(major|minor|patch)' || echo "patch")
          npx tauri-version@latest $bump_type --no-git --no-lock
          echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_ENV

          cd src-tauri && cargo update -p gitaurora

      - name: Commit updated version
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add package.json package-lock.json src-tauri/Cargo.toml src-tauri/Cargo.lock src-tauri/tauri.conf.json
          git commit -m "chore: bump version to ${{ env.VERSION }}"
          git push

      - name: Continue Workflow Dispatch
        uses: actions/github-script@v6
        if: ${{ github.event_name == 'workflow_dispatch' }}
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'main.yml',
              ref: 'main',
              headers: {
                authorization: Bearer ${{ secrets.PAT_TOKEN }},
              },
            })

  publish-tauri:
    needs: bump-version-and-publish
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'macos-latest'
            args: '--target aarch64-apple-darwin'
          - platform: 'macos-latest'
            args: '--target x86_64-apple-darwin'
          - platform: 'ubuntu-22.04'
            args: ''
          - platform: 'windows-latest'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'

      - name: Install frontend dependencies
        run: npm install

      - name: Get version
        id: get_version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # These environment variables are needed to code sign and notarize your app on macOS[1][2].
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ env.CERT_ID }}

          # Provide Apple Developer credentials to notarize the app[2].
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

          # If you use a Tauri private key for signing on other platforms, include them as well[1].
          TAURI_SIGNING_PRIVATE_KEY_PASSWORD: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY_PASSWORD }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}

          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

        with:
          tagName: app-v__VERSION__
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: false
          prerelease: false
          args: ${{ matrix.args }}

  publish-to-other-repo:
    needs: publish-tauri
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Get version
        id: get_version
        run: echo "VERSION=$(node -p \"require('./package.json').version\")" >> $GITHUB_OUTPUT

      - name: Download release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release download app-v${{ steps.get_version.outputs.VERSION }} --repo ${{ github.repository }} --dir ./assets

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: croissantlabs/gitaurora-releases
          token: ${{ secrets.PAT_TOKEN }}
          path: target-repo

      - name: Copy assets to target repository
        run: |
            mkdir -p ./target-repo/assets
            cp ./assets/latest.json ./target-repo/assets/
            cp ./assets/GitAurora_aarch64.* ./target-repo/assets/
            cp ./assets/GitAurora_x64.* ./target-repo/assets/
            cp ./assets/GitAurora_${{ steps.get_version.outputs.VERSION }}_* ./target-repo/assets/
            cd ./target-repo
            sed -i 's|https://github.com/croissantlabs/gitaurora|https://github.com/croissantlabs/gitaurora-releases|g' ./assets/latest.json
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Release app-v${{ steps.get_version.outputs.VERSION }}"
            git push

      - name: List assets
        run: |
          cd ./target-repo
          ls -R ./assets

      - name: Create release in target repository
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          cd ./target-repo
          gh release create app-v${{ steps.get_version.outputs.VERSION }} \
            --title "App v${{ steps.get_version.outputs.VERSION }}" \
            --notes "See the assets to download this version and install." \
            ./assets/GitAurora_${{ steps.get_version.outputs.VERSION }}_* \
            ./assets/GitAurora_aarch64.* \
            ./assets/GitAurora_x64.* \
            ./assets/latest.json
